"""
Language Ducks — слова для этапа «Перевод».

Каждое слово — это словарь:
    word         — само слово на иностранном языке
    language     — язык по-русски, для показа на экране
    answer       — правильный перевод
    alternatives — запасные варианты перевода, которые тоже считаются
                   верными (например «бабочка» и «мотылёк»)

Проверка ответа игрока с этим списком — в server.py. По 20 слов на
язык (100 всего), и у всех 100 слов — разные значения, чтобы за партию
(и между партиями) ничего не повторялось по смыслу. Темы вперемешку:
еда, погода, животные, дом, части тела, время, эмоции, город, одежда,
природа, школа, транспорт, музыка, спорт. Большинство слов —
узнаваемые, где можно угадать по созвучию или по школьным знаниям;
на каждый язык есть слова посложнее.
"""

WORDS = [
    # Английский
    {"word": "dog", "language": "английский", "answer": "собака",
     "alternatives": ["пёс", "песик"]},
    {"word": "apple", "language": "английский", "answer": "яблоко",
     "alternatives": []},
    {"word": "rain", "language": "английский", "answer": "дождь",
     "alternatives": []},
    {"word": "wind", "language": "английский", "answer": "ветер",
     "alternatives": []},
    {"word": "cloud", "language": "английский", "answer": "облако",
     "alternatives": ["тучка", "облачко"]},
    {"word": "bear", "language": "английский", "answer": "медведь",
     "alternatives": ["мишка"]},
    {"word": "star", "language": "английский", "answer": "звезда",
     "alternatives": ["звёздочка"]},
    {"word": "flower", "language": "английский", "answer": "цветок",
     "alternatives": ["цветочек"]},
    {"word": "key", "language": "английский", "answer": "ключ",
     "alternatives": ["ключик"]},
    {"word": "night", "language": "английский", "answer": "ночь",
     "alternatives": []},
    {"word": "fox", "language": "английский", "answer": "лиса",
     "alternatives": ["лисица", "лисичка"]},
    {"word": "duck", "language": "английский", "answer": "утка",
     "alternatives": ["уточка"]},
    {"word": "sugar", "language": "английский", "answer": "сахар",
     "alternatives": ["сахарок"]},
    {"word": "soup", "language": "английский", "answer": "суп",
     "alternatives": ["супчик"]},
    {"word": "autumn", "language": "английский", "answer": "осень",
     "alternatives": []},
    {"word": "river", "language": "английский", "answer": "река",
     "alternatives": ["речка"]},
    {"word": "mountain", "language": "английский", "answer": "гора",
     "alternatives": ["горка"]},
    {"word": "shoe", "language": "английский", "answer": "ботинок",
     "alternatives": ["туфля", "ботинки"]},
    {"word": "school", "language": "английский", "answer": "школа",
     "alternatives": []},
    {"word": "train", "language": "английский", "answer": "поезд",
     "alternatives": []},

    # Немецкий
    {"word": "der Fisch", "language": "немецкий", "answer": "рыба",
     "alternatives": ["рыбка"]},
    {"word": "die Sonne", "language": "немецкий", "answer": "солнце",
     "alternatives": ["солнышко"]},
    {"word": "die Milch", "language": "немецкий", "answer": "молоко",
     "alternatives": []},
    {"word": "die Hand", "language": "немецкий", "answer": "рука",
     "alternatives": []},
    {"word": "der Winter", "language": "немецкий", "answer": "зима",
     "alternatives": []},
    {"word": "das Ei", "language": "немецкий", "answer": "яйцо",
     "alternatives": ["яичко"]},
    {"word": "der Kaffee", "language": "немецкий", "answer": "кофе",
     "alternatives": []},
    {"word": "die Tür", "language": "немецкий", "answer": "дверь",
     "alternatives": ["дверка", "дверца"]},
    {"word": "das Pferd", "language": "немецкий", "answer": "лошадь",
     "alternatives": ["конь"]},
    {"word": "die Nase", "language": "немецкий", "answer": "нос",
     "alternatives": ["носик"]},
    {"word": "die Kuh", "language": "немецкий", "answer": "корова",
     "alternatives": ["коровка"]},
    {"word": "der Schmetterling", "language": "немецкий", "answer": "бабочка",
     "alternatives": ["мотылёк"]},
    {"word": "die Butter", "language": "немецкий", "answer": "масло",
     "alternatives": ["маслице"]},
    {"word": "der Baum", "language": "немецкий", "answer": "дерево",
     "alternatives": ["деревце"]},
    {"word": "die Stadt", "language": "немецкий", "answer": "город",
     "alternatives": ["городок"]},
    {"word": "der Mund", "language": "немецкий", "answer": "рот",
     "alternatives": ["ротик"]},
    {"word": "der Fuß", "language": "немецкий", "answer": "нога",
     "alternatives": ["ножка", "стопа"]},
    {"word": "die Musik", "language": "немецкий", "answer": "музыка",
     "alternatives": []},
    {"word": "der Rock", "language": "немецкий", "answer": "юбка",
     "alternatives": ["юбочка"]},
    {"word": "der Ball", "language": "немецкий", "answer": "мяч",
     "alternatives": ["мячик"]},

    # Испанский
    {"word": "el gato", "language": "испанский", "answer": "кот",
     "alternatives": ["кошка", "котик"]},
    {"word": "el pan", "language": "испанский", "answer": "хлеб",
     "alternatives": []},
    {"word": "la casa", "language": "испанский", "answer": "дом",
     "alternatives": ["домик"]},
    {"word": "los ojos", "language": "испанский", "answer": "глаза",
     "alternatives": ["глаз"]},
    {"word": "la luna", "language": "испанский", "answer": "луна",
     "alternatives": []},
    {"word": "el amor", "language": "испанский", "answer": "любовь",
     "alternatives": []},
    {"word": "el sombrero", "language": "испанский", "answer": "шляпа",
     "alternatives": ["шляпка"]},
    {"word": "el agua", "language": "испанский", "answer": "вода",
     "alternatives": ["водичка"]},
    {"word": "el ratón", "language": "испанский", "answer": "мышь",
     "alternatives": ["мышка"]},
    {"word": "el chocolate", "language": "испанский", "answer": "шоколад",
     "alternatives": ["шоколадка"]},
    {"word": "la fruta", "language": "испанский", "answer": "фрукт",
     "alternatives": ["фрукты"]},
    {"word": "la playa", "language": "испанский", "answer": "пляж",
     "alternatives": ["побережье"]},
    {"word": "la espalda", "language": "испанский", "answer": "спина",
     "alternatives": ["спинка"]},
    {"word": "la sonrisa", "language": "испанский", "answer": "улыбка",
     "alternatives": ["улыбочка"]},
    {"word": "el baile", "language": "испанский", "answer": "танец",
     "alternatives": ["пляска", "танцы"]},
    {"word": "el autobús", "language": "испанский", "answer": "автобус",
     "alternatives": ["автобусик"]},
    {"word": "la tormenta", "language": "испанский", "answer": "буря",
     "alternatives": ["гроза", "шторм"]},
    {"word": "la camisa", "language": "испанский", "answer": "рубашка",
     "alternatives": ["рубаха"]},
    {"word": "la primavera", "language": "испанский", "answer": "весна",
     "alternatives": []},
    {"word": "el pastel", "language": "испанский", "answer": "торт",
     "alternatives": ["пирог", "тортик"]},

    # Украинский
    {"word": "сир", "language": "украинский", "answer": "сыр",
     "alternatives": ["сырок"]},
    {"word": "сніг", "language": "украинский", "answer": "снег",
     "alternatives": ["снежок"]},
    {"word": "стіл", "language": "украинский", "answer": "стол",
     "alternatives": ["столик"]},
    {"word": "вікно", "language": "украинский", "answer": "окно",
     "alternatives": ["окошко"]},
    {"word": "вечір", "language": "украинский", "answer": "вечер",
     "alternatives": []},
    {"word": "палець", "language": "украинский", "answer": "палец",
     "alternatives": ["пальчик"]},
    {"word": "вухо", "language": "украинский", "answer": "ухо",
     "alternatives": ["ушко"]},
    {"word": "гарбуз", "language": "украинский", "answer": "тыква",
     "alternatives": ["тыковка"]},
    {"word": "парасолька", "language": "украинский", "answer": "зонт",
     "alternatives": ["зонтик"]},
    {"word": "лелека", "language": "украинский", "answer": "аист",
     "alternatives": []},
    {"word": "цибуля", "language": "украинский", "answer": "лук",
     "alternatives": ["лучок"]},
    {"word": "цукерка", "language": "украинский", "answer": "конфета",
     "alternatives": ["конфетка"]},
    {"word": "шкарпетки", "language": "украинский", "answer": "носки",
     "alternatives": ["носочки"]},
    {"word": "ліс", "language": "украинский", "answer": "лес",
     "alternatives": ["лесок"]},
    {"word": "автомобіль", "language": "украинский", "answer": "машина",
     "alternatives": ["автомобиль", "авто"]},
    {"word": "ґудзик", "language": "украинский", "answer": "пуговица",
     "alternatives": ["пуговка"]},
    {"word": "їжак", "language": "украинский", "answer": "ёж",
     "alternatives": ["ёжик"]},
    {"word": "місяць", "language": "украинский", "answer": "месяц",
     "alternatives": []},
    {"word": "ковдра", "language": "украинский", "answer": "одеяло",
     "alternatives": ["одеялко"]},
    {"word": "смуток", "language": "украинский", "answer": "грусть",
     "alternatives": ["печаль", "тоска"]},

    # Белорусский
    {"word": "кніга", "language": "белорусский", "answer": "книга",
     "alternatives": ["книжка"]},
    {"word": "птушка", "language": "белорусский", "answer": "птица",
     "alternatives": ["птичка"]},
    {"word": "сэрца", "language": "белорусский", "answer": "сердце",
     "alternatives": ["сердечко"]},
    {"word": "радасць", "language": "белорусский", "answer": "радость",
     "alternatives": ["счастье"]},
    {"word": "бульба", "language": "белорусский", "answer": "картошка",
     "alternatives": ["картофель"]},
    {"word": "вавёрка", "language": "белорусский", "answer": "белка",
     "alternatives": ["белочка"]},
    {"word": "валасы", "language": "белорусский", "answer": "волосы",
     "alternatives": []},
    {"word": "лета", "language": "белорусский", "answer": "лето",
     "alternatives": []},
    {"word": "люстэрка", "language": "белорусский", "answer": "зеркало",
     "alternatives": ["зеркальце"]},
    {"word": "гарбата", "language": "белорусский", "answer": "чай",
     "alternatives": []},
    {"word": "агурок", "language": "белорусский", "answer": "огурец",
     "alternatives": ["огурчик"]},
    {"word": "морква", "language": "белорусский", "answer": "морковь",
     "alternatives": ["морковка"]},
    {"word": "певень", "language": "белорусский", "answer": "петух",
     "alternatives": ["петушок"]},
    {"word": "рукаў", "language": "белорусский", "answer": "рукав",
     "alternatives": ["рукава"]},
    {"word": "хмара", "language": "белорусский", "answer": "туча",
     "alternatives": ["тучка"]},
    {"word": "жывот", "language": "белорусский", "answer": "живот",
     "alternatives": ["животик"]},
    {"word": "веласіпед", "language": "белорусский", "answer": "велосипед",
     "alternatives": ["велик"]},
    {"word": "перамога", "language": "белорусский", "answer": "победа",
     "alternatives": []},
    {"word": "дзядуля", "language": "белорусский", "answer": "дедушка",
     "alternatives": ["дед", "дедуля"]},
    {"word": "спалох", "language": "белорусский", "answer": "испуг",
     "alternatives": ["страх"]},
]


"""
Слова для этапа «Обманка».

Тут не про узнаваемость, а наоборот: слово должно быть настоящим, но
незнакомым русскоговорящему, а его смысл — неожиданным или смешным,
чтобы вокруг него было интересно врать. Языки — финский, норвежский,
исландский, по 20 слов на каждый (60 всего). Формат словаря тот же,
что у WORDS: answer — настоящий перевод (не длиннее двух-трёх слов,
иначе он выделяется длиной среди коротких придумок игроков),
alternatives — запасные, более развёрнутые формулировки того же
смысла (на случай, если игрок сформулирует правду другими словами).
"""

TRICK_WORDS = [
    # Финский
    {"word": "sisu", "language": "финский", "answer": "упорство",
     "alternatives": ["стойкость", "несгибаемость", "выдержка"]},
    {"word": "kalsarikänni", "language": "финский", "answer": "пьянка в трусах",
     "alternatives": ["пить дома в белье", "выпивка в нижнем белье", "пить в трусах дома одному"]},
    {"word": "myötähäpeä", "language": "финский", "answer": "испанский стыд",
     "alternatives": ["стыд за другого", "неловкость за чужого", "чувство неловкости за другого"]},
    {"word": "löyly", "language": "финский", "answer": "банный пар",
     "alternatives": ["пар в бане", "пар в сауне", "жар от каменки"]},
    {"word": "tsemppi", "language": "финский", "answer": "держись",
     "alternatives": ["не сдавайся", "давай, соберись", "пожелание удачи перед трудным делом"]},
    {"word": "kaamos", "language": "финский", "answer": "полярная ночь",
     "alternatives": ["зимняя тьма", "период без солнца", "долгая зимняя темнота на севере"]},
    {"word": "hankikanto", "language": "финский", "answer": "наст",
     "alternatives": ["крепкий наст", "плотный снежный наст", "снег, по которому можно идти не проваливаясь"]},
    {"word": "ruotsinlaiva", "language": "финский", "answer": "паром за водкой",
     "alternatives": ["паром в Швецию за спиртным", "поездка на пароме за алкоголем", "шведский паром для дешёвой выпивки"]},
    {"word": "jokamiehenoikeus", "language": "финский", "answer": "право на природу",
     "alternatives": ["право гулять где угодно", "право находиться в чужом лесу", "право доступа к любой природе"]},
    {"word": "poronkusema", "language": "финский", "answer": "оленья мера",
     "alternatives": ["мера расстояния по оленьим следам", "путь до оленьей стоянки", "расстояние, которое пройдёт олень"]},
    {"word": "avanto", "language": "финский", "answer": "прорубь",
     "alternatives": ["ледяная прорубь", "прорубь во льду"]},
    {"word": "kyykkyviini", "language": "финский", "answer": "дешёвое вино",
     "alternatives": ["вино с нижней полки", "дешёвая бормотуха", "вино эконом-класса"]},
    {"word": "kukkahattutäti", "language": "финский", "answer": "ханжа",
     "alternatives": ["морализаторша", "святоша", "занудная моралистка"]},
    {"word": "peräkamaripoika", "language": "финский", "answer": "маменькин сынок",
     "alternatives": ["взрослый сын, живущий с родителями", "домосед-неудачник"]},
    {"word": "hyppytyynytyydytys", "language": "финский", "answer": "наслаждение подушкой",
     "alternatives": ["радость от мягкой подушки", "кайф от прыжка на подушку", "удовольствие от мягкости"]},
    {"word": "morkkis", "language": "финский", "answer": "похмельный стыд",
     "alternatives": ["стыд за вчерашнее", "похмельное раскаяние", "чувство вины с похмелья"]},
    {"word": "jälkiviisas", "language": "финский", "answer": "задним умом крепок",
     "alternatives": ["умный после драки", "мудрый задним числом"]},
    {"word": "lintukoto", "language": "финский", "answer": "тихая гавань",
     "alternatives": ["райский уголок", "безопасное место", "спокойный уголок"]},
    {"word": "tarjeta", "language": "финский", "answer": "не замерзать",
     "alternatives": ["стойко переносить холод", "не мёрзнуть на морозе"]},
    {"word": "nakittaa", "language": "финский", "answer": "свалить работу",
     "alternatives": ["спихнуть неприятное дело", "переложить работу на другого"]},

    # Норвежский
    {"word": "utepils", "language": "норвежский", "answer": "пиво на улице",
     "alternatives": ["уличное пиво", "первое пиво весной на улице", "пиво на свежем воздухе"]},
    {"word": "påskekrim", "language": "норвежский", "answer": "пасхальный детектив",
     "alternatives": ["детектив на Пасху", "пасхальные детективы", "чтение детективов на Пасху"]},
    {"word": "forelsket", "language": "норвежский", "answer": "эйфория влюблённости",
     "alternatives": ["влюблённость", "эйфория от любви", "состояние влюблённости"]},
    {"word": "koselig", "language": "норвежский", "answer": "уют",
     "alternatives": ["уютность", "тепло и уют", "уютно"]},
    {"word": "harryhandel", "language": "норвежский", "answer": "шопинг за границей",
     "alternatives": ["закупки в соседней стране подешевле", "поездка за дешёвыми покупками", "шопинг-туризм за товарами подешевле"]},
    {"word": "fredagskos", "language": "норвежский", "answer": "уют пятницы",
     "alternatives": ["пятничный отдых всей семьёй", "уютный пятничный вечер с угощениями", "традиция расслабляться в пятницу вечером"]},
    {"word": "russefeiring", "language": "норвежский", "answer": "выпускной месяц",
     "alternatives": ["месяц выпускных гулянок", "долгое празднование выпуска из школы", "традиция норвежских выпускников"]},
    {"word": "pålegg", "language": "норвежский", "answer": "начинка на хлеб",
     "alternatives": ["то, что кладут на бутерброд", "бутербродная намазка", "всё, что можно положить на хлеб"]},
    {"word": "matpakke", "language": "норвежский", "answer": "школьный обед",
     "alternatives": ["бутерброды с собой", "коробка с обедом из дома", "упакованный обед для школы или работы"]},
    {"word": "vabbing", "language": "норвежский", "answer": "выпивка перед праздником",
     "alternatives": ["пить накануне выходного дня", "предпраздничная попойка", "выпивка перед официальным праздником"]},
    {"word": "dugnad", "language": "норвежский", "answer": "субботник",
     "alternatives": ["коллективный труд", "общий трудовой день", "толока"]},
    {"word": "lønningspils", "language": "норвежский", "answer": "пиво в получку",
     "alternatives": ["пиво после зарплаты", "пятничное пиво с получки"]},
    {"word": "hyttekontor", "language": "норвежский", "answer": "удалёнка на даче",
     "alternatives": ["работа с дачи", "офис на даче"]},
    {"word": "helt Texas", "language": "норвежский", "answer": "полный хаос",
     "alternatives": ["всё пошло вразнос", "бардак", "кавардак"]},
    {"word": "gruglede", "language": "норвежский", "answer": "предвкушение со страхом",
     "alternatives": ["смесь страха и радости", "тревожное предвкушение", "страх пополам с радостью"]},
    {"word": "hålke", "language": "норвежский", "answer": "гололёд",
     "alternatives": ["ледяная корка", "наледь"]},
    {"word": "janteloven", "language": "норвежский", "answer": "закон Янте",
     "alternatives": ["кодекс скромности", "правило не выделяться"]},
    {"word": "pølsevev", "language": "норвежский", "answer": "чепуха",
     "alternatives": ["ерунда", "бред", "чушь"]},
    {"word": "døgnvill", "language": "норвежский", "answer": "сбитые сутки",
     "alternatives": ["не отличить день от ночи", "путаница дня и ночи"]},
    {"word": "rumpetroll", "language": "норвежский", "answer": "головастик",
     "alternatives": ["личинка лягушки"]},

    # Исландский
    {"word": "hundslappadrífa", "language": "исландский", "answer": "безветренный снегопад",
     "alternatives": ["крупный снегопад без ветра", "снегопад крупными хлопьями", "крупные хлопья снега в безветрие"]},
    {"word": "gluggaveður", "language": "исландский", "answer": "обманчивая погода",
     "alternatives": ["обманчиво хорошая погода за окном", "хороша только с виду погода", "погода, которая хороша только из окна"]},
    {"word": "þórðargleði", "language": "исландский", "answer": "злорадство",
     "alternatives": ["радость чужой беде", "злорадствовать", "радоваться чужой неудаче"]},
    {"word": "sólarfrí", "language": "исландский", "answer": "солнечный отгул",
     "alternatives": ["отгул из-за солнечной погоды", "прогул ради солнца", "внеплановый выходной из-за хорошей погоды"]},
    {"word": "þetta reddast", "language": "исландский", "answer": "всё образуется",
     "alternatives": ["всё наладится само собой", "как-нибудь само уладится", "не переживай, всё получится"]},
    {"word": "kviðmágur", "language": "исландский", "answer": "муж свояченицы",
     "alternatives": ["муж сестры жены", "родственник через сестру жены", "муж другой сестры твоей жены"]},
    {"word": "sólarhringur", "language": "исландский", "answer": "сутки",
     "alternatives": ["день и ночь вместе", "оборот солнца", "полный оборот суток"]},
    {"word": "dagsverk", "language": "исландский", "answer": "мера площади",
     "alternatives": ["дневная норма работы в поле", "участок земли, вспаханный за день", "старинная мера земли по труду за день"]},
    {"word": "þorramatur", "language": "исландский", "answer": "исландская еда",
     "alternatives": ["зимнее угощение", "традиционная зимняя исландская еда", "исландский праздничный стол в разгар зимы"]},
    {"word": "jólaköttur", "language": "исландский", "answer": "рождественский кот",
     "alternatives": ["кот, который ест ленивых на Рождество", "исландский рождественский монстр-кот", "кот из исландских рождественских легенд"]},
    {"word": "mörgæs", "language": "исландский", "answer": "пингвин",
     "alternatives": []},
    {"word": "gæsalappir", "language": "исландский", "answer": "кавычки",
     "alternatives": ["кавычка"]},
    {"word": "bergmal", "language": "исландский", "answer": "эхо",
     "alternatives": ["отголосок"]},
    {"word": "handklæði", "language": "исландский", "answer": "полотенце",
     "alternatives": ["полотенчико"]},
    {"word": "skreppa", "language": "исландский", "answer": "отлучиться",
     "alternatives": ["сбегать по делам", "ненадолго уйти", "выскочить по делам"]},
    {"word": "vesen", "language": "исландский", "answer": "морока",
     "alternatives": ["суета", "канитель", "возня"]},
    {"word": "rúntur", "language": "исландский", "answer": "катание по кругу",
     "alternatives": ["объезд по городу", "круговая покатушка", "вечерний заезд"]},
    {"word": "þjóðvegur", "language": "исландский", "answer": "шоссе",
     "alternatives": ["трасса", "автострада"]},
    {"word": "jæja", "language": "исландский", "answer": "ну и ну",
     "alternatives": ["ну ладно", "так-так", "ну что ж"]},
    {"word": "flugdólgur", "language": "исландский", "answer": "авиахулиган",
     "alternatives": ["дебошир в самолёте", "скандалист на борту"]},
]
